# Generated by Django 4.0.4 on 2022-05-30 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.timestampedmodel')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            bases=('book.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.timestampedmodel')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
            bases=('book.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.timestampedmodel')),
                ('original_name', models.CharField(max_length=300)),
                ('edition_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('author', models.ManyToManyField(to='book.author')),
                ('category', models.ManyToManyField(to='book.category')),
            ],
            bases=('book.timestampedmodel',),
        ),
    ]
